# config.yml
target:
  - min: mse
  - mae
# find_best:
#   - adapt_lr_level
group_by:
  - dataset
  - pred_len
  - model
  - adapt_lr_level
where:
  - param_dataset: 'ECL'
  # - param_model: 'Autoformer'
ignore:
  - gpu